name: Build Aplication and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Obteniendo Codigo Fuente
        uses: actions/checkout@v3

      - name: Instalando Node v22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalando Dependencias
        run: npm install

      - name: Construyendo Aplicacion
        run: npm run build

      - name:  Obteniendo Version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Configurando Docker
        uses: docker/setup-buildx-action@v2

      - name: Iniciando Sesion Repositorio Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construyendo y Enviando Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --push -f Dockerfile \
            -t markitooo/devsonic_cl:${{ env.VERSION }} .
